### ISSUE TITLE
Making predictions from a multiple linear regression model

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/multiple-linear-regression-public-health#4]
https://carpentries-incubator.github.io/multiple-linear-regression-public-health/03-pred/index.html

Simple linear regression for public health
->
Multiple linear regression for public health

we create a tibble with the values 30, 40, 50 and 60
->
we create a tibble with Age having the values 30, 40, 50 and 60 for males and females.

Recall that 95% of 95% confidence intervals are expected 
->
Recall that this implies 95% of confidence intervals are expected

**Comment by ezherman** [comment]
@3mmaRand , I am not sure about the final comment. Does "this" refer to the R output? 

I put the "95% of 95% confidence intervals are expected (...)" there to remind students of the definition of a 95% CI.

**Comment by 3mmaRand** [comment]
Hi @ezherman I thought "95% of 95%" could confuse so wondered about dropping the 95% that describes what CI they are. Maybe adding the definite article would help:
"95% of the 95% confidence intervals are expected (...)"
Or
For 95% confidence intervals, recall that 95% of the intervals are expected......

**Comment by ezherman** [comment]
@3mmaRand gotcha, good point! I will incorporate this edit.
